const routes = require('next-routes')

module.exports = routes()
.add('newPortfolio', '/portfolios/new')
.add('portfolio', '/portfolio/:id')
.add('portfolioEdit', '/portfolios/:id/edit')
.add('userBlogsDashboard', '/blogs/dashboard')
.add('blogEditor', '/blogs/new')
.add('blogDetails', '/blogs/:slug')
.add('blogEditorUpdate', '/blogs/:id/edit')
